Added the option to set custom break tag
sstur/draft-js-utils pull request #105
Opened 2017-10-07 00:41 UTC by alxpy

The default break element is `<br>`, but now you can set custom element.

fix https://github.com/sstur/draft-js-utils/pull/93

2017-10-12 13:56 UTC, alxpy commented
@sstur what do you think about this PR?

2017-10-16 11:59 UTC, sstur requested changes
Thanks for this contribution.

Your code is good. I am OK with the option of overriding the default `BREAK`.

Few thoughts tho:
1. I don't think we should call it `breakElement` maybe just `linebreak` since it is not necessarily an "element".
2. I think we should separate the two different uses of `<br>`
   - one is for preventing collapse of an empty block element `<p><br></p>`
   - the other is for replacing `\n` in text nodes.
  They should each have their own option.

Side note, this doesn't exactly close #25 in my opinion. I think the best solution for that issue is: "add option to not render lines (blocks) which have only whitespaces?"

Regardless of #25 tho, I like your PR and I think we should split this into two options and then land it.

2017-10-16 11:59 UTC, sstur commented on packages/draft-js-export-html/README.md
> +let options = { breakElement: '<hr />'} ;
Nit: space on the left, no space on the right.

2017-10-16 11:59 UTC, sstur commented on packages/draft-js-export-html/src/__tests__/stateToHTML-test.js
> +      '<p><hr /></p>',
Let's use `<hr>` with the closing `/`

2017-10-22 12:14 UTC, alxpy commented
> 2. I think we should separate the two different uses of <br>

Make sense. I agree. How do you want to name one more option (for replacing `\n` in text nodes)?

2018-01-11 22:17 UTC, closed without merging

2020-05-31 14:40 UTC, MihaiWill commented
What happened? I can't change it anymore. All my line breaks are with '\n' instead of <br/>. Please help!